# Generated by Django 4.0 on 2022-07-14 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0003_folder_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(default='sam', on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='auth.user'),
        ),
    ]
